---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/map-coloring-book
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
